# Generated by Django 5.0.6 on 2026-05-07 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(default='XRPUSDT', max_length=100, unique=True)),
                ('name', models.CharField(default='XRPUSDT', max_length=100)),
                ('ltp', models.CharField(default='0.00', max_length=100)),
                ('tick_size', models.DecimalField(decimal_places=6, default=0.0, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, default=100000, max_digits=25)),
                ('username', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(default='Profile_image/profile.jpg', max_length=1000, upload_to='Profile_image/')),
                ('profile_description', models.CharField(default='', max_length=500)),
                ('otp_token', models.CharField(default='', max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('avg_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('total_buy_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('ltp', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('realized_profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('currencypair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.currencypair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('capital_required', models.CharField(default='100000.00', max_length=100)),
                ('json_data', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('entry_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('currencypair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.currencypair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(default='NFO', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('description', models.CharField(max_length=500)),
                ('side', models.CharField(default='BUY', max_length=50)),
                ('type', models.CharField(default='CALL', max_length=50)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='SELL', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('trigger_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('trigger_type', models.CharField(choices=[('INDEX_PERCENTAGE', 'INDEX_PERCENTAGE'), ('CUMULATIVE_PNL_PERCENTAGE', 'CUMULATIVE_PNL_PERCENTAGE'), ('CUMULATIVE_PNL_VALUE', 'CUMULATIVE_PNL_VALUE'), ('TIME_PERIOD', 'TIME_PERIOD'), ('PERCENTAGE', 'PERCENTAGE'), ('INDEX_POINTS', 'INDEX_POINTS'), ('CUSTOM', 'CUSTOM'), ('POINTS', 'POINTS')], default='PERCENTAGE', max_length=100)),
                ('action_type', models.CharField(choices=[('STOPLOSS', 'STOPLOSS'), ('TARGET', 'TARGET'), ('REPAIR', 'REPAIR'), ('TRAILING_STOPLOSS', 'TRAILING_STOPLOSS'), ('EXIT', 'EXIT'), ('BUY_EXIT', 'BUY_EXIT'), ('SELL_EXIT', 'SELL_EXIT')], default='ENTRY', max_length=100)),
                ('create_trigger', models.BooleanField(default=False)),
                ('trail_type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('POINTS', 'POINTS'), ('CUMULATIVE_PNL_VALUE', 'CUMULATIVE_PNL_VALUE')], default='PERCENTAGE', max_length=100)),
                ('trail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(default='', max_length=50)),
                ('trigger_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('order_type', models.CharField(default='LIMIT', max_length=50)),
                ('side', models.CharField(default='BUY', max_length=50)),
                ('greater_than', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('broker_order_id', models.CharField(default='', max_length=100)),
                ('trigger_type', models.CharField(choices=[('TARGET', 'TARGET'), ('STOPLOSS', 'STOPLOSS'), ('SUM_STOPLOSS', 'SUM_STOPLOSS'), ('SUM_TARGET', 'SUM_TARGET'), ('CUSTOM', 'CUSTOM'), ('TRAILING_STOPLOSS_POINTS', 'TRAILING_STOPLOSS_POINTS'), ('TRAILING_STOPLOSS_SUM', 'TRAILING_STOPLOSS_SUM'), ('ENTRY', 'ENTRY'), ('EXIT', 'EXIT')], default='STOPLOSS', max_length=50)),
                ('check_at_broker', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('TRIGGERED', 'TRIGGERED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50)),
                ('trail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('trail_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBroker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(default='<function uuid4 at 0x0000019D0F23DB20>', max_length=500, unique=True)),
                ('margin_available', models.CharField(default='', max_length=100)),
                ('margin_used', models.CharField(default='0.00', max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(default='NFO', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('condition', models.CharField(default='ENTRY', max_length=50)),
                ('side', models.CharField(default='BUY', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('order_type', models.CharField(default='MARKET', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('reason', models.CharField(default='NONE', max_length=200)),
                ('broker_order_id', models.CharField(default='', max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.position')),
                ('user_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userbroker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='User Strategy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multiplyer', models.IntegerField(default=1)),
                ('deployed', models.BooleanField(default=False)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.strategy')),
                ('user_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userbroker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='user_strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userstrategy'),
        ),
    ]
