# Generated by Django 5.0.6 on 2026-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trigger_type',
            field=models.CharField(choices=[('TIME_PERIOD', 'TIME_PERIOD'), ('INDEX_PERCENTAGE', 'INDEX_PERCENTAGE'), ('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE'), ('INDEX_POINTS', 'INDEX_POINTS'), ('CUMULATIVE_PNL_VALUE', 'CUMULATIVE_PNL_VALUE'), ('CUMULATIVE_PNL_PERCENTAGE', 'CUMULATIVE_PNL_PERCENTAGE'), ('CUSTOM', 'CUSTOM')], default='PERCENTAGE', max_length=100),
        ),
        migrations.AlterField(
            model_name='userbroker',
            name='api_key',
            field=models.CharField(default='<function uuid4 at 0x00000137B89F1A80>', max_length=500, unique=True),
        ),
    ]
