# Generated by Django 5.0.6 on 2026-06-22 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_strategysignal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backtestreport',
            new_name='apis_backte_strateg_3b595d_idx',
            old_name='apis_backte_strateg_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestreport',
            new_name='apis_backte_run_lab_466e05_idx',
            old_name='apis_backte_run_lab_idx',
        ),
        migrations.RenameIndex(
            model_name='strategysignal',
            new_name='apis_strate_strateg_dfe991_idx',
            old_name='apis_strats_strateg_idx',
        ),
        migrations.RenameIndex(
            model_name='strategysignal',
            new_name='apis_strate_signal__3210c2_idx',
            old_name='apis_strats_signal__idx',
        ),
        migrations.RenameIndex(
            model_name='strategysignal',
            new_name='apis_strate_status_bf1a96_idx',
            old_name='apis_strats_status_idx',
        ),
        migrations.AddField(
            model_name='userbroker',
            name='label',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='meta_account_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='meta_api_token_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='meta_api_token_last4',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='action',
            name='trigger_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('POINTS', 'POINTS'), ('TIME_PERIOD', 'TIME_PERIOD'), ('CUSTOM', 'CUSTOM'), ('INDEX_POINTS', 'INDEX_POINTS'), ('CUMULATIVE_PNL_VALUE', 'CUMULATIVE_PNL_VALUE'), ('CUMULATIVE_PNL_PERCENTAGE', 'CUMULATIVE_PNL_PERCENTAGE'), ('INDEX_PERCENTAGE', 'INDEX_PERCENTAGE')], default='PERCENTAGE', max_length=100),
        ),
        migrations.AlterField(
            model_name='backtestreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strategysignal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbroker',
            name='api_key',
            field=models.CharField(default='<function uuid4 at 0x000001B249D85080>', max_length=500, unique=True),
        ),
    ]
