"""Strategy Manager tables (design spec 2026-07-02 §5).

Hand-written (like 0006) to contain ONLY the four new models — autogenerated
makemigrations also emits unrelated drift ops (index renames, id/api_key
alters) caused by the legacy set-based choices, which must not ship.

Canonical schema — mirrored by SQLAlchemy in utils/models.py (this repo) and
KronosStrategies strategies/shared/models.py:
  apis_regimesnapshot, apis_managedstrategy, apis_managerconfig,
  apis_manageraction
"""
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0006_userstrategy_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegimeSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(default="XAU_USD", max_length=20)),
                ("d1_bias", models.CharField(default="neutral", max_length=10)),
                ("h4_bias", models.CharField(default="neutral", max_length=10)),
                ("vol_regime", models.CharField(choices=[("LOW", "LOW"), ("NORMAL", "NORMAL"), ("HIGH", "HIGH"), ("EXTREME", "EXTREME")], default="NORMAL", max_length=10)),
                ("trend_regime", models.CharField(choices=[("TRENDING", "TRENDING"), ("RANGING", "RANGING"), ("MIXED", "MIXED")], default="MIXED", max_length=10)),
                ("session", models.CharField(choices=[("ASIA", "ASIA"), ("LONDON", "LONDON"), ("NY", "NY"), ("OVERLAP", "OVERLAP"), ("ROLLOVER", "ROLLOVER")], default="ASIA", max_length=10)),
                ("market_closed", models.BooleanField(default=False)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("master_mode", models.CharField(choices=[("OFF", "OFF"), ("ON", "ON")], default="OFF", max_length=3)),
                ("kill_switch_loss_usd", models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ("max_concurrent_positions", models.IntegerField(default=3)),
                ("state", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagedStrategy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("slot", models.CharField(default="", max_length=20)),
                ("policy_key", models.CharField(default="", max_length=40)),
                ("policy_params", models.JSONField(blank=True, default=dict)),
                ("arm_mode", models.CharField(choices=[("OFF", "OFF"), ("PAPER", "PAPER"), ("LIVE", "LIVE")], default="OFF", max_length=5)),
                ("live_eligible", models.BooleanField(default=False)),
                ("desired_active", models.BooleanField(default=False)),
                ("last_reason", models.CharField(blank=True, default="", max_length=300)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("user_strategy", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="managed_strategy", to="apis.userstrategy")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("START", "START"), ("PAUSE", "PAUSE"), ("KILL_SWITCH", "KILL_SWITCH"), ("INFO", "INFO")], default="INFO", max_length=15)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("regime", models.JSONField(blank=True, default=dict)),
                ("managed_strategy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="apis.managedstrategy")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="regimesnapshot",
            index=models.Index(fields=["symbol", "created_at"], name="apis_regime_symbol_2ae383_idx"),
        ),
    ]
