# Generated by Django 5.0.6 on 2026-07-31 20:14
#
# NOTE: `manage.py makemigrations apis` also auto-detected pre-existing,
# unrelated model/migration-state drift (index renames on BacktestReport /
# StrategySignal, and AlterField noise on Action.trigger_type,
# BacktestReport.id, StrategySignal.id, UserBroker.api_key). That drift
# reproduces identically with a clean checkout of apis/models.py (verified
# via `git stash` + dry-run) and is unrelated to task 16 (DB index additions
# for Trigger/Position/Order). It has been deliberately excluded from this
# migration so it stays scoped to the four new indexes; the drift remains
# pending for whoever owns that follow-up.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_strategy_manager'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['condition', 'created_at'], name='idx_order_condition_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='idx_order_broker_order_id'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['symbol', 'quantity'], name='idx_position_symbol_qty'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['position', 'status'], name='idx_trigger_pos_status'),
        ),
    ]
