# Generated by Django 5.0.6 on 2026-07-31, then hand-trimmed.
#
# NOTE: makemigrations also auto-detected pre-existing, unrelated model/migration
# drift (index renames + AlterField noise on Action/BacktestReport/StrategySignal/
# UserBroker — the same recurring set documented in migration 0008's header).
# Those operations were removed; this migration contains ONLY the
# ManagerBacktestRun additions from the 2026-07-31 Manager Backtest tab plan.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_add_position_order_trigger_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('phase', models.CharField(blank=True, default='', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='managerbacktestrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='managerbacktestrun',
            index=models.Index(fields=['status', 'created_at'], name='idx_mbrun_status_created'),
        ),
    ]
