"""
Schema-surface smoke test.

Pins the exact set of top-level GraphQL Query and Mutation field names as they
exist today, so refactors of the schema plumbing (auto-discovery, dead-file
removal, import cleanups) provably do not add, drop, or rename any field.

The expected lists were generated by introspecting `apis.schema.schema` and
must only ever change when the API surface is *intentionally* changed.
"""
from django.test import SimpleTestCase

from apis.schema import schema

EXPECTED_QUERY_FIELDS = [
    "_debug",
    "accountAnalytics",
    "allBacktestReport",
    "allCurrencyPair",
    "allIndicator",
    "allPeriod",
    "allStrategy",
    "allStrategySignal",
    "allUserBrokers",
    "archivedStrategies",
    "candles",
    "getStrategy",
    "getUserPositions",
    "getheatmap",
    "getuserdata",
    "latestRegime",
    "managedStrategies",
    "managerActions",
    "managerBacktestRun",
    "managerBacktestRuns",
    "managerConfig",
    "me",
    "pnlCalendar",
    "regimeHistory",
    "totalCount",
    "user",
    "users",
]

EXPECTED_MUTATION_FIELDS = [
    "AddAccount",
    "AddStrategy",
    "AddStrategyAction",
    "ArchiveStrategy",
    "ArmStrategy",
    "CancelManagerBacktest",
    "ChangePassword",
    "ChangeStrategyStatus",
    "CreateStrategy",
    "DeleteStrategy",
    "DeleteStrategyAction",
    "DeleteUserBroker",
    "DeleteUserStrategy",
    "ExitStrategy",
    "GenerateBackTestReport",
    "Login",
    "PauseStrategy",
    "RunManagerBacktest",
    "SetManagerMode",
    "SetUserStrategyMultiplier",
    "ToggleRiskProfile",
    "ToggleTrailingStoploss",
    "UnarchiveStrategy",
    "UpdateAccount",
    "UpdateManagerConfig",
    "UpdateStrategyAction",
    "UpdateUser",
    "VerifyAccount",
    "VerifyToken",
    "tokenAuth",
    "verifyToken",
]


class SchemaSurfaceTests(SimpleTestCase):
    """The schema is built at import time; no DB access is needed."""

    def test_query_field_names_are_unchanged(self):
        actual = sorted(schema.graphql_schema.query_type.fields.keys())
        self.assertEqual(actual, EXPECTED_QUERY_FIELDS)

    def test_mutation_field_names_are_unchanged(self):
        actual = sorted(schema.graphql_schema.mutation_type.fields.keys())
        self.assertEqual(actual, EXPECTED_MUTATION_FIELDS)
